---
title: "607 Data Acquistion & Management Week 1 Assignment"
author: "Chad Bailey"
date:   "`r Sys.Date()`"
---


0. Load the selected dataset into R.

```{r}
# Original data location: "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
# Personal Git for this assignment: "https://raw.githubusercontent.com/ChadRyanBailey/607-Week1-Assignment/master/Mushroom%20Data.csv"
fileLocation <- "https://raw.githubusercontent.com/ChadRyanBailey/607-Week1-Assignment/master/Mushroom%20Data.csv"
mushrooms <- read.table(file = fileLocation, header = FALSE, sep = ",")

```


1. Add meaningful column names (using provided data dictionary). 

```{r}
names(mushrooms) <- c("edible-or-poisonous"  
                      ,"cap-shape"
                      ,"cap-surface"
                      ,"cap-color"
                      ,"bruises?"
                      ,"odor"
                      ,"gill-attachment"
                      ,"gill-spacing"
                      ,"gill-size"
                      ,"gill-color"
                      ,"stalk-shape"
                      ,"stalk-root"
                      ,"stalk-surface-above-ring"
                      ,"stalk-surface-below-ring"
                      ,"stalk-color-above-ring"
                      ,"stalk-color-below-ring"
                      ,"veil-type"
                      ,"veil-color"
                      ,"ring-number"
                      ,"ring-type"
                      ,"spore-print-color"
                      ,"population"
                      ,"habitat")
```

2. Review the first few rows of the data and a summary of the data.

```{r}
head(mushrooms)
summary(mushrooms)
```

3. Subset the data, including the column "edible-or-poisonous" and three or four other columns

```{r}
mushrooms_subset <- mushrooms[, c("edible-or-poisonous"
                                  ,"gill-spacing"
                                  ,"gill-size"
                                  ,"population"
                                  ,"habitat")]
head(mushrooms_subset)
summary(mushrooms_subset)
```


4. Replace the abbreviations used in the data
```{r}
eop <- mushrooms_subset[,"edible-or-poisonous"]
eop <- sub("e", "edible", eop)
eop <- sub("p", "poisonous", eop)
mushrooms_subset[,"edible-or-poisonous"] <-eop

gspacing <- mushrooms_subset[,"gill-spacing"]
gspacing <- sub("c", "close", gspacing)
gspacing <- sub("w", "crowded", gspacing)
mushrooms_subset[,"gill-spacing"] <- gspacing

gsize <- mushrooms_subset[,"gill-size"]
gsize <- sub("b", "broad", gsize)
gsize <- sub("n", "narrow", gsize)
mushrooms_subset[,"gill-size"] <- gsize


population <- mushrooms_subset[,"population"]
population <- sub("\\ba", "abundant", population)
population <- sub("\\bc", "clustered", population)
population <- sub("\\bn", "numerous", population)
population <- sub("\\bs", "scattered", population)
population <- sub("\\bv", "several", population)
population <- sub("\\by", "solitary", population)
mushrooms_subset[,"population"] <- population


habitat <- mushrooms_subset[,"habitat"]
habitat <- sub("\\bd", "woods", habitat)
habitat <- sub("\\bg", "grasses", habitat)
habitat <- sub("\\bl", "leaves", habitat)
habitat <- sub("\\bm", "meadows", habitat)
habitat <- sub("\\bp", "paths", habitat)
habitat <- sub("\\bu", "urban", habitat)
habitat <- sub("\\bw\\b", "waste", habitat)
mushrooms_subset[,"habitat"] <- habitat

#convert character fields back to factors
mushrooms_subset <- as.data.frame(unclass(mushrooms_subset))

#review transformed data
head(mushrooms_subset)
summary(mushrooms_subset)


```
